version: '2'
services:
  simmapservice1:
    build: ./simmapservice/
    external_links:
      -  devmaster-simmapdatabase:postgres
    ports:
      - "40005:9001"
  simmapservice2:
    build: ./simmapservice/
    external_links:
      -  devmaster-simmapdatabase:postgres
    ports:
      - "40006:9001"
  simmapservice3:
    build: ./simmapservice/
    external_links:
      -  devmaster-simmapdatabase:postgres
    ports:
      - "40007:9001"
  simmapwebsite:
    build: ./simmapeditor/
    ports:
      - "40004:9000"