version: '2'
services:
  simmapservice1:
    build: ./simmapservice/
    ports:
      - "40005:9000"
  simmapservice2:
    build: ./simmapservice/
    ports:
      - "40006:9000"
  simmapwebsite:
    build: ./simmapeditor/
    ports:
      - "40004:9000"