version: '2'
services:
  simmapservice1:
    build: ./simmapservice/
    external_links:
      -  "<prefix>-simmapdatabase:postgres"
    ports:
      - "40005:9001"
    networks:
      - <prefix>-simmapnetwork
  simmapservice2:
    build: ./simmapservice/
    external_links:
      -  "<prefix>-simmapdatabase:postgres"
    ports:
      - "40006:9001"
    networks:
      - <prefix>-simmapnetwork
  simmapservice3:
    build: ./simmapservice/
    external_links:
      -  "<prefix>-simmapdatabase:postgres"
    ports:
      - "40007:9001"
    networks:
      - <prefix>-simmapnetwork
  simmapwebsite:
    build: ./simmapeditor/
    ports:
      - "40004:9000"
networks:
  <prefix>-simmapnetwork:
    external: true