/**
 * This class is generated by jOOQ
 */
package dataaccess.database;


import dataaccess.database.tables.Link;
import dataaccess.database.tables.Network;
import dataaccess.database.tables.NetworkOptions;
import dataaccess.database.tables.Node;
import dataaccess.database.tables.records.LinkRecord;
import dataaccess.database.tables.records.NetworkOptionsRecord;
import dataaccess.database.tables.records.NetworkRecord;
import dataaccess.database.tables.records.NodeRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<LinkRecord> LINKID = UniqueKeys0.LINKID;
	public static final UniqueKey<NetworkRecord> ID = UniqueKeys0.ID;
	public static final UniqueKey<NetworkOptionsRecord> NETWORK_OPTIONSID = UniqueKeys0.NETWORK_OPTIONSID;
	public static final UniqueKey<NodeRecord> NODEID = UniqueKeys0.NODEID;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<LinkRecord, NetworkRecord> LINK__LINK_NETWORK = ForeignKeys0.LINK__LINK_NETWORK;
	public static final ForeignKey<NetworkOptionsRecord, NetworkRecord> NETWORK_OPTIONS__NETWORK_NETWORK_OPTIONS = ForeignKeys0.NETWORK_OPTIONS__NETWORK_NETWORK_OPTIONS;
	public static final ForeignKey<NodeRecord, NetworkRecord> NODE__NETWORKID = ForeignKeys0.NODE__NETWORKID;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<LinkRecord> LINKID = createUniqueKey(Link.LINK, Link.LINK.ID, Link.LINK.NETWORKID);
		public static final UniqueKey<NetworkRecord> ID = createUniqueKey(Network.NETWORK, Network.NETWORK.ID);
		public static final UniqueKey<NetworkOptionsRecord> NETWORK_OPTIONSID = createUniqueKey(NetworkOptions.NETWORK_OPTIONS, NetworkOptions.NETWORK_OPTIONS.NETWORKID, NetworkOptions.NETWORK_OPTIONS.OPTIONNAME);
		public static final UniqueKey<NodeRecord> NODEID = createUniqueKey(Node.NODE, Node.NODE.ID, Node.NODE.NETWORKID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<LinkRecord, NetworkRecord> LINK__LINK_NETWORK = createForeignKey(dataaccess.database.Keys.ID, Link.LINK, Link.LINK.NETWORKID);
		public static final ForeignKey<NetworkOptionsRecord, NetworkRecord> NETWORK_OPTIONS__NETWORK_NETWORK_OPTIONS = createForeignKey(dataaccess.database.Keys.ID, NetworkOptions.NETWORK_OPTIONS, NetworkOptions.NETWORK_OPTIONS.NETWORKID);
		public static final ForeignKey<NodeRecord, NetworkRecord> NODE__NETWORKID = createForeignKey(dataaccess.database.Keys.ID, Node.NODE, Node.NODE.NETWORKID);
	}
}
