/**
 * This class is generated by jOOQ
 */
package dataaccess.database;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.changeset_pk_id</code>
	 */
	public static final Sequence<Long> CHANGESET_PK_ID = new SequenceImpl<Long>("changeset_pk_id", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
