/**
 * This class is generated by jOOQ
 */
package dataaccess.database;


import dataaccess.database.tables.Link;
import dataaccess.database.tables.Network;
import dataaccess.database.tables.NetworkOptions;
import dataaccess.database.tables.Node;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.Link
	 */
	public static final Link LINK = dataaccess.database.tables.Link.LINK;

	/**
	 * The table public.Network
	 */
	public static final Network NETWORK = dataaccess.database.tables.Network.NETWORK;

	/**
	 * The table public.Network_Options
	 */
	public static final NetworkOptions NETWORK_OPTIONS = dataaccess.database.tables.NetworkOptions.NETWORK_OPTIONS;

	/**
	 * The table public.Node
	 */
	public static final Node NODE = dataaccess.database.tables.Node.NODE;
}
