/**
 * This class is generated by jOOQ
 */
package dataaccess.database;


import dataaccess.database.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table public.Changeset
     */
    public static final Changeset CHANGESET = dataaccess.database.tables.Changeset.CHANGESET;

    /**
     * The table public.Link
     */
    public static final Link LINK = dataaccess.database.tables.Link.LINK;

    /**
     * The table public.Link_Change
     */
    public static final LinkChange LINK_CHANGE = dataaccess.database.tables.LinkChange.LINK_CHANGE;

    /**
     * The table public.Network
     */
    public static final Network NETWORK = dataaccess.database.tables.Network.NETWORK;

    /**
     * The table public.Network_Options
     */
    public static final NetworkOptions NETWORK_OPTIONS = dataaccess.database.tables.NetworkOptions.NETWORK_OPTIONS;

    /**
     * The table public.Node
     */
    public static final Node NODE = dataaccess.database.tables.Node.NODE;

    /**
     * The table public.Node_Change
     */
    public static final NodeChange NODE_CHANGE = dataaccess.database.tables.NodeChange.NODE_CHANGE;
}
