/**
 * This class is generated by jOOQ
 */
package dataaccess.database.tables.records;


import dataaccess.database.tables.Link;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Record2;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkRecord extends UpdatableRecordImpl<LinkRecord> implements Record13<String, Integer, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Boolean, String, String, String, Integer, Date> {

	private static final long serialVersionUID = -906469258;

	/**
	 * Setter for <code>public.Link.Id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.Link.Id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.Link.NetworkId</code>.
	 */
	public void setNetworkid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.Link.NetworkId</code>.
	 */
	public Integer getNetworkid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.Link.QuadKey</code>.
	 */
	public void setQuadkey(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.Link.QuadKey</code>.
	 */
	public String getQuadkey() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.Link.Length</code>.
	 */
	public void setLength(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.Link.Length</code>.
	 */
	public BigDecimal getLength() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>public.Link.Freespeed</code>.
	 */
	public void setFreespeed(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.Link.Freespeed</code>.
	 */
	public BigDecimal getFreespeed() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>public.Link.Capacity</code>.
	 */
	public void setCapacity(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.Link.Capacity</code>.
	 */
	public BigDecimal getCapacity() {
		return (BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>public.Link.Permlanes</code>.
	 */
	public void setPermlanes(BigDecimal value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.Link.Permlanes</code>.
	 */
	public BigDecimal getPermlanes() {
		return (BigDecimal) getValue(6);
	}

	/**
	 * Setter for <code>public.Link.Oneway</code>.
	 */
	public void setOneway(Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.Link.Oneway</code>.
	 */
	public Boolean getOneway() {
		return (Boolean) getValue(7);
	}

	/**
	 * Setter for <code>public.Link.Modes</code>.
	 */
	public void setModes(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.Link.Modes</code>.
	 */
	public String getModes() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>public.Link.From</code>.
	 */
	public void setFrom(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.Link.From</code>.
	 */
	public String getFrom() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>public.Link.To</code>.
	 */
	public void setTo(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.Link.To</code>.
	 */
	public String getTo() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>public.Link.MinLevel</code>.
	 */
	public void setMinlevel(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.Link.MinLevel</code>.
	 */
	public Integer getMinlevel() {
		return (Integer) getValue(11);
	}

	/**
	 * Setter for <code>public.Link.LastModified</code>.
	 */
	public void setLastmodified(Date value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>public.Link.LastModified</code>.
	 */
	public Date getLastmodified() {
		return (Date) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<String, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<String, Integer, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Boolean, String, String, String, Integer, Date> fieldsRow() {
		return (Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<String, Integer, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Boolean, String, String, String, Integer, Date> valuesRow() {
		return (Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Link.LINK.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Link.LINK.NETWORKID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Link.LINK.QUADKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field4() {
		return Link.LINK.LENGTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field5() {
		return Link.LINK.FREESPEED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field6() {
		return Link.LINK.CAPACITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field7() {
		return Link.LINK.PERMLANES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field8() {
		return Link.LINK.ONEWAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Link.LINK.MODES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Link.LINK.FROM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Link.LINK.TO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return Link.LINK.MINLEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field13() {
		return Link.LINK.LASTMODIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getNetworkid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getQuadkey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value4() {
		return getLength();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value5() {
		return getFreespeed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value6() {
		return getCapacity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value7() {
		return getPermlanes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value8() {
		return getOneway();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getModes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getFrom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getTo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getMinlevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value13() {
		return getLastmodified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value2(Integer value) {
		setNetworkid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value3(String value) {
		setQuadkey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value4(BigDecimal value) {
		setLength(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value5(BigDecimal value) {
		setFreespeed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value6(BigDecimal value) {
		setCapacity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value7(BigDecimal value) {
		setPermlanes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value8(Boolean value) {
		setOneway(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value9(String value) {
		setModes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value10(String value) {
		setFrom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value11(String value) {
		setTo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value12(Integer value) {
		setMinlevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value13(Date value) {
		setLastmodified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord values(String value1, Integer value2, String value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, Boolean value8, String value9, String value10, String value11, Integer value12, Date value13) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LinkRecord
	 */
	public LinkRecord() {
		super(Link.LINK);
	}

	/**
	 * Create a detached, initialised LinkRecord
	 */
	public LinkRecord(String id, Integer networkid, String quadkey, BigDecimal length, BigDecimal freespeed, BigDecimal capacity, BigDecimal permlanes, Boolean oneway, String modes, String from, String to, Integer minlevel, Date lastmodified) {
		super(Link.LINK);

		setValue(0, id);
		setValue(1, networkid);
		setValue(2, quadkey);
		setValue(3, length);
		setValue(4, freespeed);
		setValue(5, capacity);
		setValue(6, permlanes);
		setValue(7, oneway);
		setValue(8, modes);
		setValue(9, from);
		setValue(10, to);
		setValue(11, minlevel);
		setValue(12, lastmodified);
	}
}
