/**
 * This class is generated by jOOQ
 */
package dataaccess.database.tables.records;


import dataaccess.database.tables.Link;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkRecord extends UpdatableRecordImpl<LinkRecord> implements Record9<String, Integer, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Boolean, String> {

	private static final long serialVersionUID = 174011033;

	/**
	 * Setter for <code>public.Link.Id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.Link.Id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.Link.NetworkId</code>.
	 */
	public void setNetworkid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.Link.NetworkId</code>.
	 */
	public Integer getNetworkid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.Link.QuadKey</code>.
	 */
	public void setQuadkey(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.Link.QuadKey</code>.
	 */
	public String getQuadkey() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.Link.length</code>.
	 */
	public void setLength(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.Link.length</code>.
	 */
	public BigDecimal getLength() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>public.Link.freespeed</code>.
	 */
	public void setFreespeed(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.Link.freespeed</code>.
	 */
	public BigDecimal getFreespeed() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>public.Link.capacity</code>.
	 */
	public void setCapacity(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.Link.capacity</code>.
	 */
	public BigDecimal getCapacity() {
		return (BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>public.Link.permlanes</code>.
	 */
	public void setPermlanes(BigDecimal value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.Link.permlanes</code>.
	 */
	public BigDecimal getPermlanes() {
		return (BigDecimal) getValue(6);
	}

	/**
	 * Setter for <code>public.Link.oneway</code>.
	 */
	public void setOneway(Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.Link.oneway</code>.
	 */
	public Boolean getOneway() {
		return (Boolean) getValue(7);
	}

	/**
	 * Setter for <code>public.Link.modes</code>.
	 */
	public void setModes(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.Link.modes</code>.
	 */
	public String getModes() {
		return (String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<String, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, Integer, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Boolean, String> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, Integer, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Boolean, String> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Link.LINK.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Link.LINK.NETWORKID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Link.LINK.QUADKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field4() {
		return Link.LINK.LENGTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field5() {
		return Link.LINK.FREESPEED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field6() {
		return Link.LINK.CAPACITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field7() {
		return Link.LINK.PERMLANES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field8() {
		return Link.LINK.ONEWAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Link.LINK.MODES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getNetworkid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getQuadkey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value4() {
		return getLength();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value5() {
		return getFreespeed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value6() {
		return getCapacity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value7() {
		return getPermlanes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value8() {
		return getOneway();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getModes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value2(Integer value) {
		setNetworkid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value3(String value) {
		setQuadkey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value4(BigDecimal value) {
		setLength(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value5(BigDecimal value) {
		setFreespeed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value6(BigDecimal value) {
		setCapacity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value7(BigDecimal value) {
		setPermlanes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value8(Boolean value) {
		setOneway(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value9(String value) {
		setModes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord values(String value1, Integer value2, String value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, Boolean value8, String value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LinkRecord
	 */
	public LinkRecord() {
		super(Link.LINK);
	}

	/**
	 * Create a detached, initialised LinkRecord
	 */
	public LinkRecord(String id, Integer networkid, String quadkey, BigDecimal length, BigDecimal freespeed, BigDecimal capacity, BigDecimal permlanes, Boolean oneway, String modes) {
		super(Link.LINK);

		setValue(0, id);
		setValue(1, networkid);
		setValue(2, quadkey);
		setValue(3, length);
		setValue(4, freespeed);
		setValue(5, capacity);
		setValue(6, permlanes);
		setValue(7, oneway);
		setValue(8, modes);
	}
}
