/**
 * This class is generated by jOOQ
 */
package dataaccess.database.tables.records;


import dataaccess.database.tables.LinkChange;
import org.jooq.Field;
import org.jooq.Record18;
import org.jooq.Record3;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Date;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LinkChangeRecord extends UpdatableRecordImpl<LinkChangeRecord> implements Record18<String, Long, Integer, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Boolean, String, String, String, Integer, Date, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = -1839327430;

    /**
     * Setter for <code>public.Link_Change.Id</code>.
     */
    public void setId(String value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>public.Link_Change.Id</code>.
     */
    public String getId() {
        return (String) getValue(0);
    }

    /**
     * Setter for <code>public.Link_Change.ChangesetNr</code>.
     */
    public void setChangesetnr(Long value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>public.Link_Change.ChangesetNr</code>.
     */
    public Long getChangesetnr() {
        return (Long) getValue(1);
    }

    /**
     * Setter for <code>public.Link_Change.NetworkId</code>.
     */
    public void setNetworkid(Integer value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>public.Link_Change.NetworkId</code>.
     */
    public Integer getNetworkid() {
        return (Integer) getValue(2);
    }

    /**
     * Setter for <code>public.Link_Change.QuadKey</code>.
     */
    public void setQuadkey(String value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>public.Link_Change.QuadKey</code>.
     */
    public String getQuadkey() {
        return (String) getValue(3);
    }

    /**
     * Setter for <code>public.Link_Change.Length</code>.
     */
    public void setLength(BigDecimal value) {
        setValue(4, value);
    }

    /**
     * Getter for <code>public.Link_Change.Length</code>.
     */
    public BigDecimal getLength() {
        return (BigDecimal) getValue(4);
    }

    /**
     * Setter for <code>public.Link_Change.Freespeed</code>.
     */
    public void setFreespeed(BigDecimal value) {
        setValue(5, value);
    }

    /**
     * Getter for <code>public.Link_Change.Freespeed</code>.
     */
    public BigDecimal getFreespeed() {
        return (BigDecimal) getValue(5);
    }

    /**
     * Setter for <code>public.Link_Change.Capacity</code>.
     */
    public void setCapacity(BigDecimal value) {
        setValue(6, value);
    }

    /**
     * Getter for <code>public.Link_Change.Capacity</code>.
     */
    public BigDecimal getCapacity() {
        return (BigDecimal) getValue(6);
    }

    /**
     * Setter for <code>public.Link_Change.Permlanes</code>.
     */
    public void setPermlanes(BigDecimal value) {
        setValue(7, value);
    }

    /**
     * Getter for <code>public.Link_Change.Permlanes</code>.
     */
    public BigDecimal getPermlanes() {
        return (BigDecimal) getValue(7);
    }

    /**
     * Setter for <code>public.Link_Change.Oneway</code>.
     */
    public void setOneway(Boolean value) {
        setValue(8, value);
    }

    /**
     * Getter for <code>public.Link_Change.Oneway</code>.
     */
    public Boolean getOneway() {
        return (Boolean) getValue(8);
    }

    /**
     * Setter for <code>public.Link_Change.Modes</code>.
     */
    public void setModes(String value) {
        setValue(9, value);
    }

    /**
     * Getter for <code>public.Link_Change.Modes</code>.
     */
    public String getModes() {
        return (String) getValue(9);
    }

    /**
     * Setter for <code>public.Link_Change.From</code>.
     */
    public void setFrom(String value) {
        setValue(10, value);
    }

    /**
     * Getter for <code>public.Link_Change.From</code>.
     */
    public String getFrom() {
        return (String) getValue(10);
    }

    /**
     * Setter for <code>public.Link_Change.To</code>.
     */
    public void setTo(String value) {
        setValue(11, value);
    }

    /**
     * Getter for <code>public.Link_Change.To</code>.
     */
    public String getTo() {
        return (String) getValue(11);
    }

    /**
     * Setter for <code>public.Link_Change.MinLevel</code>.
     */
    public void setMinlevel(Integer value) {
        setValue(12, value);
    }

    /**
     * Getter for <code>public.Link_Change.MinLevel</code>.
     */
    public Integer getMinlevel() {
        return (Integer) getValue(12);
    }

    /**
     * Setter for <code>public.Link_Change.LastModified</code>.
     */
    public void setLastmodified(Date value) {
        setValue(13, value);
    }

    /**
     * Getter for <code>public.Link_Change.LastModified</code>.
     */
    public Date getLastmodified() {
        return (Date) getValue(13);
    }

    /**
     * Setter for <code>public.Link_Change.Long1</code>.
     */
    public void setLong1(BigDecimal value) {
        setValue(14, value);
    }

    /**
     * Getter for <code>public.Link_Change.Long1</code>.
     */
    public BigDecimal getLong1() {
        return (BigDecimal) getValue(14);
    }

    /**
     * Setter for <code>public.Link_Change.Lat1</code>.
     */
    public void setLat1(BigDecimal value) {
        setValue(15, value);
    }

    /**
     * Getter for <code>public.Link_Change.Lat1</code>.
     */
    public BigDecimal getLat1() {
        return (BigDecimal) getValue(15);
    }

    /**
     * Setter for <code>public.Link_Change.Long2</code>.
     */
    public void setLong2(BigDecimal value) {
        setValue(16, value);
    }

    /**
     * Getter for <code>public.Link_Change.Long2</code>.
     */
    public BigDecimal getLong2() {
        return (BigDecimal) getValue(16);
    }

    /**
     * Setter for <code>public.Link_Change.Lat2</code>.
     */
    public void setLat2(BigDecimal value) {
        setValue(17, value);
    }

    /**
     * Getter for <code>public.Link_Change.Lat2</code>.
     */
    public BigDecimal getLat2() {
        return (BigDecimal) getValue(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, Long, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<String, Long, Integer, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Boolean, String, String, String, Integer, Date, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<String, Long, Integer, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Boolean, String, String, String, Integer, Date, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return LinkChange.LINK_CHANGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return LinkChange.LINK_CHANGE.CHANGESETNR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return LinkChange.LINK_CHANGE.NETWORKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return LinkChange.LINK_CHANGE.QUADKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return LinkChange.LINK_CHANGE.LENGTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return LinkChange.LINK_CHANGE.FREESPEED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return LinkChange.LINK_CHANGE.CAPACITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return LinkChange.LINK_CHANGE.PERMLANES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return LinkChange.LINK_CHANGE.ONEWAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return LinkChange.LINK_CHANGE.MODES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return LinkChange.LINK_CHANGE.FROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return LinkChange.LINK_CHANGE.TO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return LinkChange.LINK_CHANGE.MINLEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field14() {
        return LinkChange.LINK_CHANGE.LASTMODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field15() {
        return LinkChange.LINK_CHANGE.LONG1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field16() {
        return LinkChange.LINK_CHANGE.LAT1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field17() {
        return LinkChange.LINK_CHANGE.LONG2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field18() {
        return LinkChange.LINK_CHANGE.LAT2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getChangesetnr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getNetworkid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getQuadkey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getLength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getFreespeed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getCapacity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getPermlanes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getOneway();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getModes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getMinlevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value14() {
        return getLastmodified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value15() {
        return getLong1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value16() {
        return getLat1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value17() {
        return getLong2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value18() {
        return getLat2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value2(Long value) {
        setChangesetnr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value3(Integer value) {
        setNetworkid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value4(String value) {
        setQuadkey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value5(BigDecimal value) {
        setLength(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value6(BigDecimal value) {
        setFreespeed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value7(BigDecimal value) {
        setCapacity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value8(BigDecimal value) {
        setPermlanes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value9(Boolean value) {
        setOneway(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value10(String value) {
        setModes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value11(String value) {
        setFrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value12(String value) {
        setTo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value13(Integer value) {
        setMinlevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value14(Date value) {
        setLastmodified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value15(BigDecimal value) {
        setLong1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value16(BigDecimal value) {
        setLat1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value17(BigDecimal value) {
        setLong2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord value18(BigDecimal value) {
        setLat2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkChangeRecord values(String value1, Long value2, Integer value3, String value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, Boolean value9, String value10, String value11, String value12, Integer value13, Date value14, BigDecimal value15, BigDecimal value16, BigDecimal value17, BigDecimal value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkChangeRecord
     */
    public LinkChangeRecord() {
        super(LinkChange.LINK_CHANGE);
    }

    /**
     * Create a detached, initialised LinkChangeRecord
     */
    public LinkChangeRecord(String id, Long changesetnr, Integer networkid, String quadkey, BigDecimal length, BigDecimal freespeed, BigDecimal capacity, BigDecimal permlanes, Boolean oneway, String modes, String from, String to, Integer minlevel, Date lastmodified, BigDecimal long1, BigDecimal lat1, BigDecimal long2, BigDecimal lat2) {
        super(LinkChange.LINK_CHANGE);

        setValue(0, id);
        setValue(1, changesetnr);
        setValue(2, networkid);
        setValue(3, quadkey);
        setValue(4, length);
        setValue(5, freespeed);
        setValue(6, capacity);
        setValue(7, permlanes);
        setValue(8, oneway);
        setValue(9, modes);
        setValue(10, from);
        setValue(11, to);
        setValue(12, minlevel);
        setValue(13, lastmodified);
        setValue(14, long1);
        setValue(15, lat1);
        setValue(16, long2);
        setValue(17, lat2);
    }
}
