/**
 * This class is generated by jOOQ
 */
package dataaccess.database.tables.records;


import dataaccess.database.tables.NetworkOptions;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetworkOptionsRecord extends UpdatableRecordImpl<NetworkOptionsRecord> implements Record3<String, Integer, String> {

	private static final long serialVersionUID = -1765245718;

	/**
	 * Setter for <code>public.Network_Options.OptionName</code>.
	 */
	public void setOptionname(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.Network_Options.OptionName</code>.
	 */
	public String getOptionname() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.Network_Options.NetworkId</code>.
	 */
	public void setNetworkid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.Network_Options.NetworkId</code>.
	 */
	public Integer getNetworkid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.Network_Options.Value</code>.
	 */
	public void setValue(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.Network_Options.Value</code>.
	 */
	public String getValue() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, String> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, Integer, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<String, Integer, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return NetworkOptions.NETWORK_OPTIONS.OPTIONNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return NetworkOptions.NETWORK_OPTIONS.NETWORKID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return NetworkOptions.NETWORK_OPTIONS.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getOptionname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getNetworkid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NetworkOptionsRecord value1(String value) {
		setOptionname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NetworkOptionsRecord value2(Integer value) {
		setNetworkid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NetworkOptionsRecord value3(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NetworkOptionsRecord values(String value1, Integer value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NetworkOptionsRecord
	 */
	public NetworkOptionsRecord() {
		super(NetworkOptions.NETWORK_OPTIONS);
	}

	/**
	 * Create a detached, initialised NetworkOptionsRecord
	 */
	public NetworkOptionsRecord(String optionname, Integer networkid, String value) {
		super(NetworkOptions.NETWORK_OPTIONS);

		setValue(0, optionname);
		setValue(1, networkid);
		setValue(2, value);
	}
}
