/**
 * This class is generated by jOOQ
 */
package dataaccess.database.tables;


import dataaccess.database.Keys;
import dataaccess.database.Public;
import dataaccess.database.tables.records.NetworkRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Network extends TableImpl<NetworkRecord> {

	private static final long serialVersionUID = -793033982;

	/**
	 * The reference instance of <code>public.Network</code>
	 */
	public static final Network NETWORK = new Network();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<NetworkRecord> getRecordType() {
		return NetworkRecord.class;
	}

	/**
	 * The column <code>public.Network.Name</code>.
	 */
	public final TableField<NetworkRecord, String> NAME = createField("Name", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.Network.Id</code>.
	 */
	public final TableField<NetworkRecord, Integer> ID = createField("Id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.Network</code> table reference
	 */
	public Network() {
		this("Network", null);
	}

	/**
	 * Create an aliased <code>public.Network</code> table reference
	 */
	public Network(String alias) {
		this(alias, NETWORK);
	}

	private Network(String alias, Table<NetworkRecord> aliased) {
		this(alias, aliased, null);
	}

	private Network(String alias, Table<NetworkRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<NetworkRecord> getPrimaryKey() {
		return Keys.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<NetworkRecord>> getKeys() {
		return Arrays.<UniqueKey<NetworkRecord>>asList(Keys.ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Network as(String alias) {
		return new Network(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Network rename(String name) {
		return new Network(name, null);
	}
}
