/**
 * This class is generated by jOOQ
 */
package dataaccess.database.tables;


import dataaccess.database.Keys;
import dataaccess.database.Public;
import dataaccess.database.tables.records.NetworkOptionsRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class NetworkOptions extends TableImpl<NetworkOptionsRecord> {

    private static final long serialVersionUID = 1740584378;

    /**
     * The reference instance of <code>public.Network_Options</code>
     */
    public static final NetworkOptions NETWORK_OPTIONS = new NetworkOptions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NetworkOptionsRecord> getRecordType() {
        return NetworkOptionsRecord.class;
    }

    /**
     * The column <code>public.Network_Options.OptionName</code>.
     */
    public final TableField<NetworkOptionsRecord, String> OPTIONNAME = createField("OptionName", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>public.Network_Options.NetworkId</code>.
     */
    public final TableField<NetworkOptionsRecord, Integer> NETWORKID = createField("NetworkId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.Network_Options.Value</code>.
     */
    public final TableField<NetworkOptionsRecord, String> VALUE = createField("Value", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * Create a <code>public.Network_Options</code> table reference
     */
    public NetworkOptions() {
        this("Network_Options", null);
    }

    /**
     * Create an aliased <code>public.Network_Options</code> table reference
     */
    public NetworkOptions(String alias) {
        this(alias, NETWORK_OPTIONS);
    }

    private NetworkOptions(String alias, Table<NetworkOptionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private NetworkOptions(String alias, Table<NetworkOptionsRecord> aliased, Field<?>[] parameters) {
        super(alias, Public.PUBLIC, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<NetworkOptionsRecord> getPrimaryKey() {
        return Keys.NETWORK_OPTIONSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<NetworkOptionsRecord>> getKeys() {
        return Arrays.<UniqueKey<NetworkOptionsRecord>>asList(Keys.NETWORK_OPTIONSID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<NetworkOptionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<NetworkOptionsRecord, ?>>asList(Keys.NETWORK_OPTIONS__NETWORK_NETWORK_OPTIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NetworkOptions as(String alias) {
        return new NetworkOptions(alias, this);
    }

    /**
     * Rename this table
     */
    public NetworkOptions rename(String name) {
        return new NetworkOptions(name, null);
    }
}
